#theme: jekyll-theme-minimal
#logo: /assets/img/logo.png
#description: Minimal is a theme for GitHub Pages.
markdown: CommonMarkGhPages
commonmark: # To make <details> work
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]